version: "3"

services:
  qchatgpt:
    image: rockchin/qchatgpt:latest
    volumes:
      - ./data:/app/data
      - ./plugins:/app/plugins
    ports:
      - 8080:8080
    restart: on-failure:3
    # 根据具体环境配置网络